### ISSUE TITLE
Using MOE 1.x build library with MOE 2.x

### ISSUE THREAD

**Issue by Berstanio** [multi-os-engine/multi-os-engine#179]
I'm maintaining the libGDX moe backend and it should support MOE 1.x and MOE 2.x.
I'm applying the "moe-sdk" gradle plugin (version 1.9 currently).
However the problem is now, that the MOE 1.9 plugin injects the dependencie to the java8support jar, as a "api" target:
https://github.com/multi-os-engine/moe-plugin-gradle/blob/cbe8f87e12a4e147d1bcb2472bb9a834d4862a38/src/main/java/org/moe/gradle/AbstractMoePlugin.java#L385-L388

When now declaring the artifact, that was build against MOE 1.9, as a dependencie in a MOE 2.x project, the import fails. The reason is, that it can't find the java8support artifact, since it doesn't exist in MOE 2.x.

```:ios:main: Could not find multi-os-engine:java8support:1.9.0.
Searched in the following locations:
[...]
  - file:/Users/berstanio/.moe/moe-sdk-2.0.0-SNAPSHOT/tools/java8support.jar
Required by:
    project :ios > com.badlogicgames.gdx:gdx-backend-moe:1.11.1-SNAPSHOT
```

I'm not 100% sure about the fix. It would seem reasonable to me, to use compileOnly instead of api for all moe jars, when using "moe-sdk". Or just setting the java8support jar to compileOnly, or even exclude it, on using moe as a library. Since as I understand it, the jar is only used for doing a moe build, right?

**Comment by Noisyfox** [comment]
~Yeah I think it make sense to make it compileOnly for moe-sdk module.~

I think we could remove this java8support jar from moe-sdk module completely after a bit thought. This jar is there so that the application module can be compiled using the MOE jars as bootstrap class, and dex2oat won't give us class not found error. However the module with moe-sdk are compiled using normal JDK, and will not be dex-ed on its own - the application module does that - so there is no need to have this jar in the moe-sdk module at all.

**Comment by Noisyfox** [comment]
Could you give this PR a try and see if it solves this issue?
