### ISSUE TITLE
Locale.getDefault() and NSLocale.currentLocale() don't match

### ISSUE THREAD

**Issue by kisg** [multi-os-engine/multi-os-engine#82]
It should be investigated, whether these 2 Locale representations should match in MOE, and update the runtime library if necessary.

**Comment by martinellimarco** [comment]
I've encountered this bug today, NSLocale.currentLocale() returns the right locale but Locale.getDefault() always returns en_US.

As a workaround I'm using this in my code:
`Locale.forLanguageTag(NSLocale.currentLocale().languageCode())`

**Comment by sdyura** [comment]
this is causing me a big problem as a library i use has Locale.getDefault() code inside it, and uses that to get world region information, and i cant change the code inside the plane java lib to the ios specific suggestion

i found this workaround that needs to run at the very start of the app:

        NSLocale iOSlocale = NSLocale.currentLocale();
        String locale = iOSlocale.localeIdentifier();
        Locale javaLocale = Locale.forLanguageTag(locale.replace('_','-'));
        Locale.setDefault(javaLocale);

**Comment by Noisyfox** [comment]
Yeah I think I could add some code to MOE that set the java default locale the same as NSLocale.

**Comment by Noisyfox** [comment]
The question is, should the Locale.getDefault() automatically updating when NSLocale changed? Also I don't know if it's possible to implement `NSLocale.autoupdatingCurrentLocale` in Java's Locale.

**Comment by sdyura** [comment]
i am not sure in what situations Locale changes, if it happens while the app is in the background then it can also do that update when the app comes back to foreground, but maybe this is such a rare case and with an easy workaround (restart the app) that it does not matter, i am sure many apps take a copy of the locale at the start and do not even bother checking if it has changed in the lifetime of the app.

i wrote this bit of code to test it conversion is working correctly and it seems to pass with no error

        java.util.List<String> iosLocales = NSLocale.availableLocaleIdentifiers();
        java.util.List<Locale> javaLocales = Arrays.asList(Locale.getAvailableLocales());
        for (String locale : iosLocales) {
            Locale test = Locale.forLanguageTag(locale.replace('_','-'));
            if (!javaLocales.contains(test)) {
                throw new RuntimeException("fail for " + locale);
            }
        }

**Comment by Noisyfox** [comment]
Java's `Locale` has an very important difference to `NSLocale`: you are able to change the Java's Locale's default locale progarmmly, however you won't be able to change `NSLocale.currentLocale`, unless you swizzle it. This means there is no gaurantee of the consistence between `Locale.getDefault()` and `NSLocale.currentLocale`. What I could do at best is to set the `Locale.getDefault()` the same as `NSLocale.currentLocale` when the app starts, then the framework just don't do anything if these two values deviate.

The thing that confuses me is the existence of `NSLocale.autoupdatingCurrentLocale`, because it seems to indicate that the system's locale can change while the app is still running. However it seems that if you change the locale in system settings the app will be killed by system, so I don't know what's the purpose of this. Or is there a way of keeping app running when the locale changes?

I think it's sufficient to just set the default language the same as system locale when the app starts, as this is also what Android is doing https://developer.android.com/reference/java/util/Locale#getDefault()

**Comment by Noisyfox** [comment]
Could you try the latest 1.9 snapshot and see if it solve the problem.

**Comment by sdyura** [comment]
i have tried 1.9 but i had a error trying to run it: https://discord.com/channels/794140704585547808/799248610915123220/925160515708256286

**Comment by Noisyfox** [comment]
> i have tried 1.9 but i had a error trying to run it: https://discord.com/channels/794140704585547808/799248610915123220/925160515708256286

Should be fixed now

**Comment by sdyura** [comment]
it does build now, and i have tested 1.9 and Locale.getDefault() does seem to be fixed! thanks a lot!

**Comment by Noisyfox** [comment]
This need to be verified/ported to MOE 2.0 as well.

**Comment by Noisyfox** [comment]
The default locale is set during SVM image build time according to the document https://www.graalvm.org/reference-manual/native-image/Resources/#locales

So we have to add extra code in Java to change it based on device locale, maybe in https://github.com/multi-os-engine/moe-core/blob/a9a00085ca473e41d65e72719b127b935bd4ed3a/moe.apple/moe.platform.ios/src/main/java/org/moe/IOSLauncher.java

**Comment by sdyura** [comment]
on iOS you do sometimes need to do "Locale.setDefault" and you do it with:

NSUserDefaults.standardUserDefaults().setObject(["fr"], forKey: "AppleLanguages")
NSUserDefaults.standardUserDefaults().synchronize()

(from: https://stackoverflow.com/a/27675498 )

but unless it is done very early in loading the app, it would require the app to be restarted to take affect.

this is needed to make sure that system alerts match the language of the rest of the app if the developer of the app wants to give the user the option to change the language of the app from inside the app. otherwise most of the app will be in one language but all the system alerts will be in the default language of the phone.

there is prob not much MOE can do about this, as you dont want to be forcing a restarts when the language is changed.
